<?php

require_once dirname(__FILE__).'/../../model/DonationCanDataAccess.php';

/**
 * Test class for DonationCanDataAccess.
 * Generated by PHPUnit on 2011-11-03 at 23:20:50.
 */
class DonationCanDataAccessTest extends PHPUnit_Framework_TestCase {
    /**
     * @var DonationCanDataAccess
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DonationCanDataAccess(null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testMigrate_database().
     */
    public function testMigrate_database() {
        $this->assertEquals(2,2);
    }

    

}
?>